@M000_HostAddress = http://localhost:5166

GET {{M000_HostAddress}}/weatherforecast/GetPrettyDate
Accept: application/json

###

GET {{M000_HostAddress}}/weatherforecast/GetCurrentDate
Accept: application/json

###

GET {{M000_HostAddress}}/weatherforecast/GetCurrentTime
Accept: application/json

###

GET {{M000_HostAddress}}/weatherforecast/GetCounterEntries
Accept: application/json

### Get all movies
GET {{M000_HostAddress}}/api/moviestore/allmovies
Accept: application/json

### Create movie
POST {{M000_HostAddress}}/api/moviestore/NewMovie
Content-Type: application/json
Accept: application/json
 
{
 "id": 5,
 "title": "Pulp Fiction",
 "description": "Some iconic movie",
 "price": "5.99",
 "genre": 0
}